//> using scala 3
//> using dep org.scalameta::munit::1.2.4

import scala.annotation.tailrec

/** You are given two strings word1 and word2. Merge the strings by adding
  * letters in alternating order, starting with word1. If a string is longer
  * than the other, append the additional letters onto the end of the merged
  * string.
  */
def mergeAlternately(word1: String, word2: String): String =
  word1.zipAll(word2, "", "").map { case (a, b) => s"$a$b" }.mkString

/** You are given two strings s and t. String t is generated by random shuffling
  * string s and then add one more letter at a random position. Return the
  * letter that was added to t.
  *
  * The solution uses the XOR property that XOR'ing the same value twice leads
  * to 0, e.g. 5 ^ 5 = 0 Start: acc = 0 Character 'a' (code 97): acc = 0 ^ 97 =
  * 97 Character 'b' (code 98): acc = 97 ^ 98 = 195 Character 'a' (code 97): acc =
  * 195 ^ 97 = 98 (the 'a's canceled!) Character 'b' (code 98): acc = 98 ^ 98 =
  * 0 (the 'b's canceled!) Character 'c' (code 99): acc = 0 ^ 99 = 99
  */
def findTheDifference(s: String, t: String): Char = {
  (s + t).foldLeft(0)((acc, char) => acc ^ char.toInt).toChar
}

/** Given a string s, find the length of the longest substring without duplicate
  * characters.
  */
def lengthOfLongestSubstring(s: String): Int = {
  s.scanLeft("")((resStr, curChar) =>
    resStr.substring(1 + resStr.indexOf(curChar)) + curChar
  ).map(_.length)
    .reduce(Math.max)
}

/** Given two strings needle and haystack, return the index of the first
  * occurrence of needle in haystack, or -1 if needle is not part of haystack.
  */
def strStr(haystack: String, needle: String): Int = {
  haystack.indexOf(needle)
}

/** Given two strings s and t, return true if t is an of s, and false otherwise.
  */
def isAnagram(s: String, t: String): Boolean = {
  s.sorted == t.sorted
}

/** Given an array of integers nums and an integer target, return indices of the
  * two numbers such that they add up to target.
  */
def twoSum(nums: Array[Int], target: Int): Array[Int] = {
  @tailrec
  def twoSum(index: Int, previous: Map[Int, Int]): Array[Int] = {
    previous.get(target - nums(index)) match {
      case Some(previousIndex) => Array(previousIndex, index)
      case None => twoSum(index + 1, previous ++ Map(nums(index) -> index))
    }
  }

  twoSum(0, Map.empty)
}

/** Find all unique triplets in an array that sum to zero.
  */
// def threeSum(nums: Array[Int]): Array[Array[Int]] {
//   nums. 
// }

@main def deck(): Unit = {
  println("run 'scala-cli test deck.scala' to execute the tests")
}

class deckTest extends munit.FunSuite {
  test("mergeAlternately") {
    assert(mergeAlternately("abcd", "pq") == "apbqcd")
  }
  test("findTheDifference") {
    assert(findTheDifference("abc", "abcy") == 'y')
  }
  test("lengthOfLongestSubstring") {
    assert(lengthOfLongestSubstring("abcabcbb") == 3)
  }
  test("strStr") {
    assert(strStr("sadbutsad", "sad") == 0)
  }
  test("isAnagram") {
    assert(isAnagram("anagram", "nagaram"))
  }
  test("twoSum") {
    assert(twoSum(Array(2, 7, 11, 15), 9) sameElements Array(0, 1))
    assert(twoSum(Array(3, 2, 4), 6) sameElements Array(1, 2))
    assert(twoSum(Array(3, 3), 6) sameElements Array(0, 1))
  }
  
  test("threeSum") {
    // assert(threeSum(Array(-1, 0, 1, 2, -1, -4), ))
    // assert(threeSum(Array(1, 2, 3, 4, 5), ))
    // assert(threeSum(Array(0, 0, 0, 0), ))
    // assert(threeSum(Array(-4, -1, -1, 0, 1, 2, 2), ))
    // assert(threeSum(Array(-10, -7, -3, -1, 0, 3, 7, 10), ))
    // assert(threeSum(Array(-3, -5, -7, -9), ))
  }
}
